# Generated by Django 4.0 on 2021-12-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("url", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artistName", models.CharField(default="", max_length=70)),
                ("name", models.CharField(max_length=150)),
                ("releaseDate", models.DateField()),
                ("kind", models.CharField(max_length=20)),
                ("artistId", models.BigIntegerField()),
                ("artistUrl", models.TextField(default="", max_length=255)),
                ("contentAdvisoryRating", models.CharField(max_length=30, null=True)),
                ("artworkUrl100", models.TextField(default="", max_length=255)),
                ("rank", models.IntegerField(default=0)),
                ("url", models.TextField(default="", max_length=255)),
                (
                    "genres",
                    models.ManyToManyField(related_name="tracks", to="api.Genre"),
                ),
            ],
        ),
    ]
